#!/usr/bin/env python3

import os 
import sys
from datetime import datetime, timezone
import csv 
import argparse

def list_expense() -> None:
    print("list expense")

def update_expense() -> None:
    print("update_expense")

def delete_expense() -> None:
    print("delete_expense")

def summary_expense() -> None:
    print("summary_expense")

def add_expense(desc,amount) -> None:
    print(desc)
    print(amount)

parser = argparse.ArgumentParser(description='expense tracking')

subparsers = parser.add_subparsers(dest='operation', help='Available operations')

add_parser = subparsers.add_parser("add_expense", help="add expense in the sheet")
add_parser.add_argument("--description", type=str)
add_parser.add_argument("--amount", type=int)
add_parser.set_defaults(func=add_expense)

list_parser = subparsers.add_parser("list_expense", help="list expense in the sheet")
list_parser.set_defaults(func=list_expense)

delete_parser = subparsers.add_parser("delete_expense", help="delete expense in the sheet")
delete_parser.set_defaults(func=delete_expense)

update_parser = subparsers.add_parser("update_expense", help="update expense in the sheet")
update_parser.set_defaults(func=update_expense)

summary_parser = subparsers.add_parser("summary_expense", help="summary expense in the sheet")
summary_parser.set_defaults(func=summary_expense)

args = parser.parse_args()   

if hasattr(args, 'func'):

    if args.operation == "add_expense":
        args.func(args.description, args.amount)
    if args.operation == "list_expense":
        args.func()
    if args.operation == "delete_expense":
        args.func()
    if args.operation == "update_expense":
        args.func()
    if args.operation == "summary_expense":
        args.func()
